"""One-way futures position accounting used by the backtest engine."""

from dataclasses import dataclass
from decimal import Decimal

from trading_bot.domain import OrderSide
from trading_bot.simulator.models import SimulatedFill


@dataclass(slots=True)
class PositionLedger:
    """Track signed position, average entry price, and gross realized PnL."""

    quantity: Decimal = Decimal("0")
    average_entry_price: Decimal = Decimal("0")
    realized_pnl: Decimal = Decimal("0")

    def apply_fill(self, fill: SimulatedFill) -> Decimal:
        """Apply a fill and return the realized PnL generated by that fill."""

        if fill.side is OrderSide.BUY:
            realized = self._apply_buy(fill.price, fill.quantity)
        else:
            realized = self._apply_sell(fill.price, fill.quantity)
        self.realized_pnl += realized
        return realized

    def unrealized_pnl(self, mark_price: Decimal) -> Decimal:
        """Mark the current signed position to market."""

        if self.quantity > 0:
            return (mark_price - self.average_entry_price) * self.quantity
        if self.quantity < 0:
            return (self.average_entry_price - mark_price) * abs(self.quantity)
        return Decimal("0")

    def _apply_buy(self, price: Decimal, quantity: Decimal) -> Decimal:
        if self.quantity >= 0:
            new_quantity = self.quantity + quantity
            self.average_entry_price = (
                self.average_entry_price * self.quantity + price * quantity
            ) / new_quantity
            self.quantity = new_quantity
            return Decimal("0")

        closing_quantity = min(quantity, abs(self.quantity))
        realized = (self.average_entry_price - price) * closing_quantity
        new_quantity = self.quantity + quantity
        if new_quantity < 0:
            self.quantity = new_quantity
        elif new_quantity == 0:
            self.quantity = Decimal("0")
            self.average_entry_price = Decimal("0")
        else:
            self.quantity = new_quantity
            self.average_entry_price = price
        return realized

    def _apply_sell(self, price: Decimal, quantity: Decimal) -> Decimal:
        if self.quantity <= 0:
            current_short_quantity = abs(self.quantity)
            new_short_quantity = current_short_quantity + quantity
            self.average_entry_price = (
                self.average_entry_price * current_short_quantity + price * quantity
            ) / new_short_quantity
            self.quantity = -new_short_quantity
            return Decimal("0")

        closing_quantity = min(quantity, self.quantity)
        realized = (price - self.average_entry_price) * closing_quantity
        new_quantity = self.quantity - quantity
        if new_quantity > 0:
            self.quantity = new_quantity
        elif new_quantity == 0:
            self.quantity = Decimal("0")
            self.average_entry_price = Decimal("0")
        else:
            self.quantity = new_quantity
            self.average_entry_price = price
        return realized
